class Transaction:
    def __init__ (self):
        self.site_code=""
        self.device_id=""
        self.device_name=""
        self.ip_address=""
        self.host_name=""
        self.software_version=""
        self.serial_number=""
        self.timezone_name=""
        self.start_time=""
        self.end_time=""
        self.file_name=""
        self.in_count=""
        self.out_count=""
        self.name=""
        self.transaction_date=""
        self.status=""
        self.http_port=""
        self.https_port=""
        self.mac_address=""
        self.week=""
        self.day=""